build-deb: make --no-target the default

diff --git a/ci/build-deb b/ci/build-deb
--- a/ci/build-deb
+++ b/ci/build-deb
@@ -12,24 +12,25 @@ D="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 #
 # This should be run from the root of the ripgrep repo.
 
-TARGET=x86_64-unknown-linux-musl
+TARGET=''
 while (( $# )); do
     case "$1" in
         --target)
+            if [[ -z "$2" ]]; then
+                echo >2 "Error: missing argument to --target"
+                exit 1
+            fi
             TARGET="$2"
             shift
-            ;;
-        --no-target)
-            NO_TARGET=1
             ;;
     esac
     shift
 done
 
-if (( NO_TARGET )); then
-    TARGET_ARGS=()
-else
+if [[ -n "$TARGET" ]]; then
     TARGET_ARGS=(--target "$TARGET")
+else
+    TARGET_ARGS=()
 fi
 
 if ! command -V cargo-deb > /dev/null 2>&1; then
